app:
  upload:
    path: "C:/erp/uploads"
  base-url: "http://localhost:8080"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: INFO
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    com.jaasielsilva.portalceo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.tool.schema: DEBUG
