name: Build e Dockerize Portal CEO

on:
  push:
    branches: [ "main" ]  # ou o nome da sua branch principal (ex: master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar o código do repositório
      - name: Checkout código
        uses: actions/checkout@v4

      # 2. Configurar o Java 17
      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Gerar o .jar
      - name: Build com Maven
        run: mvn clean package -DskipTests

      # 4. Build da imagem Docker
      - name: Build imagem Docker
        run: docker build -t portal-ceo .

      # (opcional) Enviar pro Docker Hub
      # - name: Login no Docker Hub
      #   run: echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
      # - name: Push da imagem
      #   run: docker push portal-ceo